# Generated by Django 3.2.12 on 2022-04-07 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('features_mail', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='owner',
        ),
    ]
